### ISSUE TITLE
terminate called after throwing an instance of 'Magick::ErrorCoder'

### ISSUE THREAD

**Issue by AderynCrow** [backspace-phill/betterButtonMaker#1]
terminate called after throwing an instance of 'Magick::ErrorCoder'
  what():  betterButtonMaker.elf: Read Exception `JPGFlags/Zodiacgender_2_by_pride_flags_dch4zfz-pre.jpg_masked_with_overlay_image2.png' @ error/png.c/MagickPNGErrorHandler/1492
Aborted (core dumped)
![Zodiacgender_2_by_pride_flags_dch4zfz-pre](https://github.com/backspace-phill/betterButtonMaker/assets/65494883/60a8eda0-2ca6-4aac-863e-738909da3e4d)
![Zodiacgender_2_by_pride_flags_dch4zfz-pre jpg_masked_with_overlay_image2](https://github.com/backspace-phill/betterButtonMaker/assets/65494883/9f223860-068a-4dc2-a75e-b5a1bd898108)

**Comment by backspace-phill** [comment]
Error not reproducable with sent picture
maybe compile without O3 and with -ggdb as flags and run it in gdb while doing what you are doing
